// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzArnKQ0IJS-nIuutXrG-D9ROrImtpBQE',
    appId: '1:300990281821:web:f46a2d4cd51b080222f5b4',
    messagingSenderId: '300990281821',
    projectId: 'chat-app-3ef19',
    authDomain: 'chat-app-3ef19.firebaseapp.com',
    storageBucket: 'chat-app-3ef19.appspot.com',
    measurementId: 'G-EL3BYXT2W7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt9z4auVMk08LEROhPxv0FxvvSyEz0bqQ',
    appId: '1:300990281821:android:6966fd401f1f7dcb22f5b4',
    messagingSenderId: '300990281821',
    projectId: 'chat-app-3ef19',
    storageBucket: 'chat-app-3ef19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTjWwzY9Zz1JeJCEHw9Aul5I0dKE94lY8',
    appId: '1:300990281821:ios:4879e2b392f9bf0722f5b4',
    messagingSenderId: '300990281821',
    projectId: 'chat-app-3ef19',
    storageBucket: 'chat-app-3ef19.appspot.com',
    iosClientId: '300990281821-7g6d6kmotako5raq11heuemvcn9686ik.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTjWwzY9Zz1JeJCEHw9Aul5I0dKE94lY8',
    appId: '1:300990281821:ios:419ebae2a8cdddc222f5b4',
    messagingSenderId: '300990281821',
    projectId: 'chat-app-3ef19',
    storageBucket: 'chat-app-3ef19.appspot.com',
    iosClientId: '300990281821-7snls4j446777m34gvgglph4qbq1miun.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
